version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - api-network
      
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - api-network
      
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    environment:

      POSTGRES_USER: admin
      POSTGRES_PASSWORD: F9x#1Vq3mZ8!Tr2n
      POSTGRES_DB: catalog-book
    ports:
      - "5432:5432"
    networks:
      - api-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge