version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    environment:

      POSTGRES_USER: admin
      POSTGRES_PASSWORD: F9x#1Vq3mZ8!Tr2n
      POSTGRES_DB: catalog-book
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
