spring:
  application:
    name: books

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog-book
    username: admin
    password: F9x#1Vq3mZ8!Tr2n
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

server:
  port: 3000


logging:
  level:
    org.springframework.data.redis.cache: DEBUG