spring:
  application:
    name: books
  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 3000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
